In [1]:
import pandas as pd
import numpy as np

In [53]:
data = pd.DataFrame(
    [
        [1.0, 6.5, 3.0],
        [1.0, np.nan, np.nan],
        [np.nan, np.nan, np.nan],
        [np.nan, 6.5, 3.0],
    ]
)
data["3"] = pd.Series(list(np.arange(4)))
data

0    1    2  3
0  1.0  6.5  3.0  0
1  1.0  NaN  NaN  1
2  NaN  NaN  NaN  2
3  NaN  6.5  3.0  3

In [54]:
mapping = {1.0: "Done", np.nan: "Not done"}
data["status"] = data[0].map(mapping)
data

0    1    2  3    status
0  1.0  6.5  3.0  0      Done
1  1.0  NaN  NaN  1      Done
2  NaN  NaN  NaN  2  Not done
3  NaN  6.5  3.0  3  Not done

In [57]:
mapping = {0: "k1", 1: "k2", 2: "k3", "3": "k4"}
data.columns = data.columns.map(mapping)
data

k1   k2   k3  k4       NaN
0  1.0  6.5  3.0   0      Done
1  1.0  NaN  NaN   1      Done
2  NaN  NaN  NaN   2  Not done
3  NaN  6.5  3.0   3  Not done

In [61]:
def convert_to_upper(x):
    try:
        return x.upper()
    except:
        return x


data.rename(index=float, columns=convert_to_upper)

K1   K2   K3  K4       NaN
0.0  1.0  6.5  3.0   0      Done
1.0  1.0  NaN  NaN   1      Done
2.0  NaN  NaN  NaN   2  Not done
3.0  NaN  6.5  3.0   3  Not done

In [75]:
data.index = np.arange(1, 5)
data.rename(columns={np.nan:"Status"},inplace=True)

In [77]:
data.rename(columns)

K1   K2   K3  K4    Status
1  1.0  6.5  3.0   0      Done
2  1.0  NaN  NaN   1      Done
3  NaN  NaN  NaN   2  Not done
4  NaN  6.5  3.0   3  Not done

In [16]:
strings = ["a", "as", "bat", "car", "dove", "python"]

In [17]:
unique_lenghts = set(map(len, strings))
print(unique_lenghts)

{1, 2, 3, 4, 6}


In [18]:
strings_positions = {k: v for k, v in enumerate(strings)}
print(strings_positions)

{0: 'a', 1: 'as', 2: 'bat', 3: 'car', 4: 'dove', 5: 'python'}


In [19]:
def square_volume(x, y, z=1):
    volume = x * y * z
    return volume

In [20]:
square_volume(2, 2, 2)

8

In [21]:
strings = ["foo", "card", "bar", "aaaa", "abab"]

In [22]:
strings.sort(key=lambda word: len(set(word)))
print(strings)

['aaaa', 'foo', 'abab', 'bar', 'card']


In [23]:
all_data = [
    ["John", "Emily", "Michael", "Mary", "Steven"],
    ["Maria", "Juan", "Javier", "Natalia", "Pilar"],
]
names_2a = [name for l in all_data for name in l if name.count("a") > 1]

In [24]:
names_2a

['Maria', 'Natalia']

In [25]:
import numpy as np

data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [26]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [27]:
data.dtype

dtype('float64')

In [28]:
data1 = [6, 7.5, 8, 0, 1]

In [29]:
arr1 = np.array(data1)

In [30]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [31]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
arr2 = np.array(data2)

In [32]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
import numpy as np

arr = np.array([[2, 5.6, 7.8], [9.6, 5.6, 2], [10, 6.6, 8]], dtype=np.int64)

In [36]:
arr

array([[ 2,  5,  7],
       [ 9,  5,  2],
       [10,  6,  8]])

In [37]:
arr[1, :2]

array([9, 5])

In [38]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])

In [39]:
arr = names == "w"

In [40]:
arr

array([False, False, False, False, False, False, False])

In [41]:
data[data < 0] = 0

In [42]:
data[[0, 1, 2]]

array([[4, 7],
       [0, 2],
       [0, 6]])

In [43]:
arr = np.arange(1, 15).reshape(7, 2)

In [44]:
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [45]:
arr[[1, 3, 5]][:, :1]

array([[ 3],
       [ 7],
       [11]])

In [46]:
arr1 = np.array([[3, 4], [5, 7]])
arr2 = np.array([[2, 3], [4, 9]])

In [47]:
arr1.T

array([[3, 5],
       [4, 7]])

In [48]:
A = np.array(
    [
        [12, 13, 14, 12, 16, 14, 11, 10, 9],
        [11, 14, 12, 15, 15, 16, 10, 12, 11],
        [10, 12, 12, 15, 14, 16, 10, 12, 12],
        [9, 11, 16, 15, 14, 16, 15, 12, 10],
        [12, 11, 16, 14, 10, 12, 16, 12, 13],
        [10, 15, 16, 14, 14, 14, 16, 15, 12],
        [13, 17, 14, 10, 14, 11, 14, 15, 10],
        [10, 16, 12, 14, 11, 12, 14, 18, 11],
        [10, 19, 12, 14, 11, 12, 14, 18, 10],
        [14, 22, 17, 19, 16, 17, 18, 17, 13],
        [10, 16, 12, 14, 11, 12, 14, 18, 11],
        [10, 16, 12, 14, 11, 12, 14, 18, 11],
        [10, 19, 12, 14, 11, 12, 14, 18, 10],
        [14, 22, 12, 14, 11, 12, 14, 17, 13],
        [10, 16, 12, 14, 11, 12, 14, 18, 11],
    ]
)
B = A < 15
print(B.astype(dtype="int64"))

[[1 1 1 1 0 1 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 1 0 1 1 1]
 [1 1 0 0 1 0 0 1 1]
 [1 1 0 1 1 1 0 1 1]
 [1 0 0 1 1 1 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 1 1 1 1 0 1]]


In [49]:
x = np.array([3, 4, 6, 10, 24, 89, 45, 43, 46, 99, 100])
x[x % 3 == 0] = 42
print(x)

[ 42   4  42  10  42  89  42  43  46  42 100]


In [50]:
names = np.array(["Carolina", "Samantha", "Catalina", "Clara", "Carolina"])
consumo = np.array([43, 56, 98, 54, 67])
print(consumo[names == "Carolina"])

[43 67]


In [51]:
x = np.array([3, 4, 6, 10, 24, 89, 45, 43, 46, 99, 100])
print(x[[0, 3, -1]])

[  3  10 100]


In [52]:
a = np.array(
    [
        [0.0, 0.0, 0.0, 0.0],
        [1.0, 1.0, 1.0, 1.0],
        [2.0, 2.0, 2.0, 2.0],
        [3.0, 3.0, 3.0, 3.0],
        [4.0, 4.0, 4.0, 4.0],
        [5.0, 5.0, 5.0, 5.0],
        [6.0, 6.0, 6.0, 6.0],
        [7.0, 7.0, 7.0, 7.0],
    ]
)
print(a[[2, 5, 7]][1:, 1:3])

[[5. 5.]
 [7. 7.]]


In [53]:
names = ["Juan", "Ana", "Camila"]
for i, j in enumerate(names):
    print(i, j)

0 Juan
1 Ana
2 Camila


In [54]:
import numpy as np

samples = np.random.standard_normal(10)

In [55]:
x = np.arange(-5, 6)
y = np.arange(-5, 6)
gridx, gridy = np.meshgrid(x, y)
gridz = np.sqrt(gridx**2 + gridy**2)
print(gridz)

[[7.07106781 6.40312424 5.83095189 5.38516481 5.09901951 5.
  5.09901951 5.38516481 5.83095189 6.40312424 7.07106781]
 [6.40312424 5.65685425 5.         4.47213595 4.12310563 4.
  4.12310563 4.47213595 5.         5.65685425 6.40312424]
 [5.83095189 5.         4.24264069 3.60555128 3.16227766 3.
  3.16227766 3.60555128 4.24264069 5.         5.83095189]
 [5.38516481 4.47213595 3.60555128 2.82842712 2.23606798 2.
  2.23606798 2.82842712 3.60555128 4.47213595 5.38516481]
 [5.09901951 4.12310563 3.16227766 2.23606798 1.41421356 1.
  1.41421356 2.23606798 3.16227766 4.12310563 5.09901951]
 [5.         4.         3.         2.         1.         0.
  1.         2.         3.         4.         5.        ]
 [5.09901951 4.12310563 3.16227766 2.23606798 1.41421356 1.
  1.41421356 2.23606798 3.16227766 4.12310563 5.09901951]
 [5.38516481 4.47213595 3.60555128 2.82842712 2.23606798 2.
  2.23606798 2.82842712 3.60555128 4.47213595 5.38516481]
 [5.83095189 5.         4.24264069 3.60555128 3.16227766

In [56]:
# Using lists
l1 = [1.1, 1.2, 1.3, 1.4, 1.5]
l2 = [2.1, 2.2, 2.3, 2.4, 2.5]
cond = [True, False, True, True, False]
l3 = [(l1[i] if c == True else l2[i]) for i, c in enumerate(cond)]
print(l3)

[1.1, 2.2, 1.3, 1.4, 2.5]


In [57]:
# Using where function
xarr = np.array(l1)
yarr = np.array(l2)
cond_arr = np.array(cond)
result = np.where(cond_arr, xarr, 0)
print(result)

[1.1 0.  1.3 1.4 0. ]


In [58]:
arr = np.random.standard_normal((4, 4))
print(arr, "\n")
arr = np.where(arr > 0, 2, arr)
print(arr)

[[-1.23514487  0.06961329  0.05344887 -0.34809139]
 [ 0.07568149  0.15871151 -1.19727397  1.11960046]
 [-0.11508469  1.11943611  1.00624154 -0.13944758]
 [-2.26766268  0.02504494  1.78393394 -1.1545357 ]] 

[[-1.23514487  2.          2.         -0.34809139]
 [ 2.          2.         -1.19727397  2.        ]
 [-0.11508469  2.          2.         -0.13944758]
 [-2.26766268  2.          2.         -1.1545357 ]]


In [59]:
arr = np.random.standard_normal((5, 4))
print(arr, "\n")

[[ 0.73177058  2.05592321  0.79887091  1.08689407]
 [ 0.88567112 -0.62398228  0.21565238 -0.71190006]
 [-0.15203887 -0.86838372  0.19141386  0.4833134 ]
 [-0.24359864 -1.36879353  0.79887854  1.05530104]
 [-0.34042786 -0.71588199 -0.99257084 -1.75765265]] 



In [60]:
arr.std()

0.9415442537927001

In [61]:
import numpy as np

arr = np.array([0.0773, -0.6839, -0.7208, 1.1206, -0.0548, -0.0824])
arr.sort()
print(arr)

[-0.7208 -0.6839 -0.0824 -0.0548  0.0773  1.1206]


In [62]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
unique_names = np.unique(names)
print(unique_names)

['Bob' 'Joe' 'Will']


In [63]:
bobs = np.in1d(names, "Bob")
bobs.sum()

2

In [64]:
x = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
y = np.array([[6.0, 23.0], [-1, 7], [8, 9]])
print(np.dot(x, y))

[[ 28.  64.]
 [ 67. 181.]]


In [65]:
import numpy as np

arr = np.arange(10, 20, 1, dtype=np.int64).reshape((2, 5))
print(arr)

[[10 11 12 13 14]
 [15 16 17 18 19]]


In [66]:
import pandas as pd

champions = pd.Series(
    ["Italy", "Spain", "Germany", "France", "Argentina"],
    index=[2006, 2010, 2014, 2018, 2022],
)
print(champions)

2006        Italy
2010        Spain
2014      Germany
2018       France
2022    Argentina
dtype: object


In [67]:
ages = pd.Series([24, 65, 28, 15], index=["Juan", "Margarita", "Steven", "Paula"])

In [68]:
population = {"Colombia": 50, "Argentina": 45, "United States": 332}
population_s = pd.Series(population)
print(population_s)

Colombia          50
Argentina         45
United States    332
dtype: int64


In [69]:
complete_names = ["Juan Zapata", "Margarita Zapata", "Steven Posada", "Paula Duarte"]
ages.index = complete_names
print(ages)

Juan Zapata         24
Margarita Zapata    65
Steven Posada       28
Paula Duarte        15
dtype: int64


In [70]:
income = pd.Series([24, 65, 28, 15], index=["Juan", "Margarita", "Steven", "Paula"])
expense = pd.Series([58, 85, 65, 12], index=["Juan", "Margarita", "Steven", "Paula"])

In [71]:
income.name = "Income"
print(income)

Juan         24
Margarita    65
Steven       28
Paula        15
Name: Income, dtype: int64


In [72]:
# Series
# Attributes  (values,index,name)

import pandas as pd

ages = pd.Series([34, 54, 12], index=["Camila", "Sebastian", "Carlos"], name="Ages")
print(ages.index)

Index(['Camila', 'Sebastian', 'Carlos'], dtype='object')


In [73]:
# DataFrame

data = {
    "state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
    "year": [2000, 2001, 2002, 2001, 2002, 2003],
    "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2],
}
frame = pd.DataFrame(
    data, columns=["year", "state", "pop", "pop2050"], index=range(1, 7)
)
print(frame)

   year   state  pop pop2050
1  2000    Ohio  1.5     NaN
2  2001    Ohio  1.7     NaN
3  2002    Ohio  3.6     NaN
4  2001  Nevada  2.4     NaN
5  2002  Nevada  2.9     NaN
6  2003  Nevada  3.2     NaN


In [74]:
frame["state"]

1      Ohio
2      Ohio
3      Ohio
4    Nevada
5    Nevada
6    Nevada
Name: state, dtype: object

In [75]:
import pandas as pd

s = pd.Series([13, 56, 34], index=range(1, 4))
print(s)

1    13
2    56
3    34
dtype: int64


In [76]:
import numpy as np

ser = pd.Series(np.arange(3.0))

In [77]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [78]:
ser[:1]

0    0.0
dtype: float64

In [79]:
import pandas as pd
import numpy as np

ser1 = pd.Series([1, 2, 3, 4], index=list("abcd"))
df = pd.DataFrame(np.zeros((3, 4)), index=list("abc"))

In [80]:
df

0    1    2    3
a  0.0  0.0  0.0  0.0
b  0.0  0.0  0.0  0.0
c  0.0  0.0  0.0  0.0

In [81]:
ser1

a    1
b    2
c    3
d    4
dtype: int64

In [82]:
df.add(ser1, axis=0)

0    1    2    3
a  1.0  1.0  1.0  1.0
b  2.0  2.0  2.0  2.0
c  3.0  3.0  3.0  3.0
d  NaN  NaN  NaN  NaN

In [83]:
df = pd.DataFrame(np.random.standard_normal((3, 3)))
df

0         1         2
0  0.125534 -0.395274  0.272798
1  0.046630  0.431843 -0.024255
2  0.888542  1.452936 -0.250892

In [84]:
ser = pd.Series([3, 6, 8, 4], index=list("oftn"))
ser

o    3
f    6
t    8
n    4
dtype: int64

In [85]:
df = pd.DataFrame()

In [86]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank(ascending=False, method="first")

0    1.0
1    7.0
2    2.0
3    3.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [87]:
df

Empty DataFrame
Columns: []
Index: []

In [88]:
df.rank(ascending=False, axis=1)

Empty DataFrame
Columns: []
Index: []

In [89]:
import pandas as pd

df = pd.read_csv(
    "./examples/ex1.csv", names=["a", "b", "c", "d", "message"], skiprows=[1, 3]
)
df

a   b   c     d message
0  1   2   3   NaN   hello
1  5   6   7   8.0   world
2  9  10  11  12.0     foo

In [90]:
header = list("abc")
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
d = dict(zip(header, zip(*l)))
d

{'a': (1, 4, 7), 'b': (2, 5, 8), 'c': (3, 6, 9)}

In [91]:
import pandas as pd

df = pd.read_csv(
    "./examples/ex1.csv", comment="#", names=["c1", "c2", "c3", "c4", "word"]
)
df.to_csv("./examples/ex2.csv", index=None, na_rep=0)

In [92]:
import json

df = pd.read_json("./examples/obj_juan.json")
df.iloc[0, 0] = "Manuel"
df.to_json("./examples/obj_manuel.json")

In [93]:
import pandas as pd

tables = pd.read_html("./examples/FDIC_ Failed Bank List.html")
failures = tables[0]
failures["año"] = failures["Closing DateClosing"].map(lambda x: int(x[-5:]))
failures

Bank NameBank           CityCity StateSt  CertCert  \
0           Heartland Tri-State Bank            Elkhart      KS     25851   
1                First Republic Bank      San Francisco      CA     59017   
2                     Signature Bank           New York      NY     57053   
3                Silicon Valley Bank        Santa Clara      CA     24735   
4                  Almena State Bank             Almena      KS     15426   
5         First City Bank of Florida  Fort Walton Beach      FL     16748   
6               The First State Bank      Barboursville      WV     14361   
7                 Ericson State Bank            Ericson      NE     18265   
8   City National Bank of New Jersey             Newark      NJ     21111   
9                      Resolute Bank             Maumee      OH     58317   
10             Louisa Community Bank             Louisa      KY     58112   
11              The Enloe State Bank             Cooper      TX     10716   

                Acquiring InstitutionAI Closing DateClosing  FundFund   año  
0                Dream First Bank, N.A.       July 28, 2023     10544  2023  
1             JPMorgan Chase Bank, N.A.         May 1, 2023     10543  2023  
2                   Flagstar Bank, N.A.      March 12, 2023     10540  2023  
3   First–Citizens Bank & Trust Company      March 10, 2023     10539  2023  
4                           Equity Bank    October 23, 2020     10538  2020  
5             United Fidelity Bank, fsb    October 16, 2020     10537  2020  
6                        MVB Bank, Inc.       April 3, 2020     10536  2020  
7            Farmers and Merchants Bank   February 14, 2020     10535  2020  
8                       Industrial Bank    November 1, 2019     10534  2019  
9                    Buckeye State Bank    October 25, 2019     10533  2019  
10    Kentucky Farmers Bank Corporation    October 25, 2019     10532  2019  
11                   Legend Bank, N. A.        May 31, 2019     10531  2019

In [94]:
failures["año"].value_counts().sort_values(ascending=False)

año
2023    4
2020    4
2019    4
Name: count, dtype: int64

In [99]:
df = pd.read_excel("./examples/centro_de_control_maquilas.xlsx", sheet_name="Maquilas")
# Data cleaning


def convert_g_to_kg(x):
    if x > 1000:
        return x / 1000
    else:
        return x


df["Tostado (kg)"] = df["Tostado (kg)"].map(convert_g_to_kg)
df["Tostado (kg)"].mean()

14.920399999999999

In [101]:
import requests

url = "https://api.github.com/repos/pandas-dev/pandas/issues"
resp = requests.get(url)
resp

<Response [200]>

In [107]:
data = resp.json()
df = pd.DataFrame(data, columns=["id", "number", "title"])
df

id  number                                              title
0   1907685025   55233                  Typo: 'whenlines' -> 'when lines'
1   1907678016   55232  BUG: `read_csv()` silently ignores out-of-rang...
2   1907392574   55231  ENH: Export (a subset of?) pandas._typing for ...
3   1907219997   55230  BUG: pandas, s3fs, and pyarrow  raises OSError...
4   1906858640   55229                                         RLS: 2.1.2
5   1906821298   55228  BUG: Get deprecation warning from `Series` con...
6   1906746956   55227  BUG: Interchange object data buffer has the wr...
7   1906564156   55226  ENH: Support for list of formats in pd.to_date...
8   1906285254   55225  ENH: Series.reset_index() should support "name...
9   1906267379   55224  BUG: Series.value_counts with sort=False retur...
10  1905530743   55223  BUG: `read_excel` with both `usecols` and `dty...
11  1904148036   55214  BUILD: pandas build failing on Gitpod due to M...
12  1904094381   55213  BUG: support non-nanos Timedelta objects in Py...
13  1904026341   55212  BUG: `df1.merge(df2, on='ds', how='outer')` no...
14  1903417694   55204  ENH: `rsuffix` parameter of `pandas.DataFrame....
15  1903191625   55202  PERF: `.iloc[:, :len(columns)+1]` in case of m...
16  1903100230   55200  BUG: Comment in ODS-file gets included in stri...
17  1902653988   55197  ENH: Auto-detect text encoding to avoid Unicod...
18  1902533291   55196  BUG: ExcelWriter set_column with num_format da...
19  1902350703   55194  BUG: `DataFrame.var()` with `axis=1` returns `...
20  1901694114   55188  BUG: DataFrame.style.to_latex() does not allow...
21  1901561244   55187                                              DOC: 
22  1900659899   55181  BUG: DataFrame.mode() fails on sparse integer ...
23  1899772995   55179                                DEP: Use Cython 3.0
24  1899758754   55178  ENH: set `__module__` on top-level public objects
25  1899498875   55174                DEPR: Index.where and Index.putmask
26  1899492709   55173  BUG: .rolling() returns incorrect values when ...
27  1899478513   55171  ENH: set __module__ for objects in pandas pd.D...
28  1899477866   55170  BUILD: meson build step generate_version.py fa...
29  1899472824   55169  BUG: Pandas column rename function now working...