In [203]:
strings = ["a", "as", "bat", "car", "dove", "python"]

In [204]:
unique_lenghts=set(map(len,strings))
print(unique_lenghts)

{1, 2, 3, 4, 6}


In [205]:
strings_positions={k:v for k,v in enumerate(strings)}
print(strings_positions)

{0: 'a', 1: 'as', 2: 'bat', 3: 'car', 4: 'dove', 5: 'python'}


In [206]:
def square_volume(x,y,z=1):
    volume=x*y*z
    return volume

In [207]:
square_volume(2,2,2)

8

In [208]:
strings = ["foo", "card", "bar", "aaaa", "abab"]

In [209]:
strings.sort(key=lambda word:len(set(word)))
print(strings)

['aaaa', 'foo', 'abab', 'bar', 'card']


In [210]:
all_data = [["John", "Emily", "Michael", "Mary", "Steven"],["Maria", "Juan", "Javier", "Natalia", "Pilar"]]
names_2a=[name for l in all_data for name in l if name.count("a")>1]

In [211]:
names_2a  

['Maria', 'Natalia']

In [212]:
import numpy as np
data=np.array([[1.5,-0.1,3],[0,-3,6.5]])

In [213]:
data+data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [214]:
data.dtype

dtype('float64')

In [215]:
data1=[6,7.5,8,0,1]

In [216]:
arr1=np.array(data1)

In [217]:
arr1    

array([6. , 7.5, 8. , 0. , 1. ])

In [218]:
data2=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
arr2=np.array(data2)

In [219]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [220]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [221]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [222]:
import numpy as np
arr=np.array([[2,5.6,7.8],
              [9.6,5.6,2],
              [10,6.6,8]],
             dtype=np.int64)

In [223]:
arr

array([[ 2,  5,  7],
       [ 9,  5,  2],
       [10,  6,  8]])

In [224]:
arr[1,:2]

array([9, 5])

In [225]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])

In [226]:
arr = names=="w"

In [227]:
arr

array([False, False, False, False, False, False, False])

In [228]:
data[data<0]=0

In [229]:
data[[0,1,2]]

array([[4, 7],
       [0, 2],
       [0, 6]])

In [230]:
arr=np.arange(1,15).reshape(7,2)

In [231]:
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [240]:
arr[[1,3,5]][:,:1]

array([[ 3],
       [ 7],
       [11]])

In [252]:
arr1=np.array([[3, 4],[5, 7]])
arr2=np.array([[2, 3],[4, 9]])

In [253]:
arr1.T

array([[3, 5],
       [4, 7]])

In [258]:
A = np.array([
[12, 13, 14, 12, 16, 14, 11, 10,  9],
[11, 14, 12, 15, 15, 16, 10, 12, 11],
[10, 12, 12, 15, 14, 16, 10, 12, 12],
[ 9, 11, 16, 15, 14, 16, 15, 12, 10],
[12, 11, 16, 14, 10, 12, 16, 12, 13],
[10, 15, 16, 14, 14, 14, 16, 15, 12],
[13, 17, 14, 10, 14, 11, 14, 15, 10],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 17, 19, 16, 17, 18, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 12, 14, 11, 12, 14, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11]])
B = A<15
print(B.astype(dtype="int64"))

[[1 1 1 1 0 1 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 1 0 1 1 1]
 [1 1 0 0 1 0 0 1 1]
 [1 1 0 1 1 1 0 1 1]
 [1 0 0 1 1 1 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 1 1 1 1 0 1]]


In [263]:
x=np.array([3,4,6,10,24,89,45,43,46,99,100])
x[x%3==0]=42 
print(x)

[ 42   4  42  10  42  89  42  43  46  42 100]


In [266]:
names=np.array(["Carolina","Samantha","Catalina","Clara","Carolina"])
consumo=np.array([43,56,98,54,67])
print(consumo[names=="Carolina"])

[43 67]


In [268]:
x=np.array([3,4,6,10,24,89,45,43,46,99,100])
print(x[[0,3,-1]])


[  3  10 100]


In [275]:
a=np.array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])
print(a[[2,5,7]][1:,1:3])

[[5. 5.]
 [7. 7.]]


In [1]:
names=["Juan","Ana","Camila"]
for i,j in enumerate(names):
    print(i,j)

0 Juan
1 Ana
2 Camila


In [2]:
import numpy as np
samples=np.random.standard_normal(10)

In [8]:
x=np.arange(-5,6)
y=np.arange(-5,6)
gridx,gridy=np.meshgrid(x,y)
gridz=np.sqrt(gridx**2+gridy**2)
print(gridz)

[[7 6 5 5 5 5 5 5 5 6 7]
 [6 5 5 4 4 4 4 4 5 5 6]
 [5 5 4 3 3 3 3 3 4 5 5]
 [5 4 3 2 2 2 2 2 3 4 5]
 [5 4 3 2 1 1 1 2 3 4 5]
 [5 4 3 2 1 0 1 2 3 4 5]
 [5 4 3 2 1 1 1 2 3 4 5]
 [5 4 3 2 2 2 2 2 3 4 5]
 [5 5 4 3 3 3 3 3 4 5 5]
 [6 5 5 4 4 4 4 4 5 5 6]
 [7 6 5 5 5 5 5 5 5 6 7]]


In [15]:
# Using lists
l1=[1.1, 1.2, 1.3, 1.4, 1.5]
l2=[2.1, 2.2, 2.3, 2.4, 2.5]
cond=[True, False, True, True, False]
l3=[(l1[i] if c==True else l2[i]) for i,c in enumerate(cond)]
print(l3)

[1.1, 2.2, 1.3, 1.4, 2.5]


In [19]:
# Using where function
xarr=np.array(l1)
yarr=np.array(l2)
cond_arr=np.array(cond)
result=np.where(cond_arr,xarr,0)
print(result)

[1.1 0.  1.3 1.4 0. ]


In [25]:
arr=np.random.standard_normal((4,4))
print(arr,"\n")
arr=np.where(arr>0,2,arr)
print(arr)

[[ 0.07184889  0.75507413  0.25626419  0.19219367]
 [ 1.09637423  0.68058692 -0.55741679 -0.04125884]
 [-0.11275086 -1.04787508  1.02727836  0.3307569 ]
 [-0.04621213  1.95792906  0.89761264  0.69115252]] 

[[ 2.          2.          2.          2.        ]
 [ 2.          2.         -0.55741679 -0.04125884]
 [-0.11275086 -1.04787508  2.          2.        ]
 [-0.04621213  2.          2.          2.        ]]


In [30]:
arr=np.random.standard_normal((5,4))
print(arr,"\n")

[[-1.62733692 -0.12969695 -0.67181713 -0.1500508 ]
 [-0.27764795  0.21497197  2.32743715  0.01457793]
 [-1.76600497 -1.40165189  0.78143344 -1.29245975]
 [-0.42530752 -0.90907468 -0.31480329  1.17675707]
 [-0.66908785  0.3026071   0.74306117 -1.01787743]] 



In [35]:
arr.std()

0.9840245610763947

In [4]:
import numpy as np
arr=np.array([ 0.0773, -0.6839, -0.7208,  1.1206, -0.0548, -0.0824])
arr.sort()
print(arr)

[-0.7208 -0.6839 -0.0824 -0.0548  0.0773  1.1206]


In [5]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
unique_names=np.unique(names)
print(unique_names)

['Bob' 'Joe' 'Will']


In [8]:
bobs=np.in1d(names,"Bob")
bobs.sum()

2

In [9]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(np.dot(x,y))

[[ 28.  64.]
 [ 67. 181.]]


In [2]:
import numpy as np
arr=np.arange(10,20,1,dtype=np.int64).reshape((2,5))
print(arr)

[[10 11 12 13 14]
 [15 16 17 18 19]]


In [28]:
import pandas as pd
champions=pd.Series(["Italy","Spain","Germany","France","Argentina"],index=[2006,2010,2014,2018,2022])
print(champions)


2006        Italy
2010        Spain
2014      Germany
2018       France
2022    Argentina
dtype: object


In [50]:
ages=pd.Series([24,65,28,15],index=["Juan","Margarita","Steven","Paula"])

In [32]:
population={"Colombia":50,"Argentina":45,"United States":332}
population_s=pd.Series(population)
print(population_s)

Colombia          50
Argentina         45
United States    332
dtype: int64


In [33]:
complete_names=["Juan Zapata","Margarita Zapata","Steven Posada","Paula Duarte"]
ages.index=complete_names
print(ages)

Juan Zapata         24
Margarita Zapata    65
Steven Posada       28
Paula Duarte        15
dtype: int64


In [70]:
income=pd.Series([24,65,28,15],index=["Juan","Margarita","Steven","Paula"])
expense=pd.Series([58,85,65,12],index=["Juan","Margarita","Steven","Paula"])

In [71]:
income.name="Income"
print(income)

Juan         24
Margarita    65
Steven       28
Paula        15
Name: Income, dtype: int64


In [11]:
#Series
#Attributes  (values,index,name)

import pandas as pd

ages=pd.Series([34,54,12],index=["Camila","Sebastian","Carlos"],name="Ages")
print(ages.index)

Index(['Camila', 'Sebastian', 'Carlos'], dtype='object')


In [22]:
#DataFrame

data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame=pd.DataFrame(data,columns=["year","state","pop","pop2050"],index=range(1,7))
print(frame)

   year   state  pop pop2050
1  2000    Ohio  1.5     NaN
2  2001    Ohio  1.7     NaN
3  2002    Ohio  3.6     NaN
4  2001  Nevada  2.4     NaN
5  2002  Nevada  2.9     NaN
6  2003  Nevada  3.2     NaN


In [23]:
frame["state"]

1      Ohio
2      Ohio
3      Ohio
4    Nevada
5    Nevada
6    Nevada
Name: state, dtype: object

In [5]:
import pandas as pd
s=pd.Series([13,56,34],index=range(1,4))
print(s)

1    13
2    56
3    34
dtype: int64


In [7]:
import numpy as np
ser=pd.Series(np.arange(3.))

In [8]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [9]:
ser[:1]

0    0.0
dtype: float64