In [10]:
# Write a NumPy program to test whether none of the elements of a given array are zero. 
import numpy as np
x = np.array([0, 1, 2, 3])
if True in (x==0):
    print("zero(s) found")
else:
    print("no zero(s) found")

zero(s) found


In [11]:
# Write a NumPy program to test whether none of the elements of a given array are zero. 
# solved with .all() method 
import numpy as np
x = np.array([0, 1, 2, 3])
if x.all(0):
    print("no zero(s) found")
else:
    print("zero(s) found")

zero(s) found


In [12]:
# Write a NumPy program to test if any of the elements of a given array are non-zero. 
import numpy as np
x = np.array([0, 1, 2, 3])
if False in (x==0):
    print("no-zero element(s)")
else:
    print("all zeros")

no-zero element(s)


In [18]:
# Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

x = np.array([3, 5])
y = np.array([2, 5])
print(x>y)
print(x>=y)
print(x<y)
print(x<=y)

[ True False]
[ True  True]
[False False]
[False  True]


In [23]:
# Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives. 
np.array([[0]*10,[1]*10,[5]*10]).reshape(1,30)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5]])

In [25]:
#Write a NumPy program to create an array of integers from 30 to 70.
np.arange(30,71)


array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [27]:
# Write a NumPy program to create an array of all even integers from 30 to 70.
np.arange(30,71,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [28]:
# Write a NumPy program to create a 3x3 identity matrix (16)

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
# Write a NumPy program to multiply the values of two given vectors (24)
x = np.array([1, 8, 3, 5])
y= np.array([1,2,3,4])
print(x*y)

[ 1 16  9 20]


In [33]:
# Write a NumPy program to find the number of rows and columns in a given matrix. (26)
m= np.arange(10,22).reshape((3, 4))
print("The number of rows is",m.shape[0],"and the number of columns is",m.shape[1])


The number of rows is 3 and the number of columns is 4


In [52]:
# Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0. (28)
m=np.ones([10,10])
m[1:-1,1:-1]=0
print(m)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [57]:
# Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5. (29)

m=np.eye(5)
v=np.arange(1,6)
print(m*v)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [71]:
# Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal (30)
m=np.zeros((4,4))
m[0::2,1::2]=1
m[1::2,0::2]=1
print(m)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [72]:
# Write a NumPy program to compute the inner product of two given vectors. (33)
x = np.array([4, 5])
y = np.array([7, 10])
print(np.dot(x,y))

78


In [74]:
# Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.
x=np.zeros(10)
x[5]=11
print(x)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [75]:
# Write a NumPy program to reverse an array (the first element becomes the last).
x = np.arange(12, 38)
x[::-1]

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

In [78]:
# Write a NumPy program to convert an array to a floating type.
x = np.arange(1,5)
y=x.astype(dtype="float64")
print(y)


[1. 2. 3. 4.]


In [81]:
# Write a NumPy program to create an 8x8 matrix and fill it with a checkerboard pattern.
m=np.zeros((8,8))
for i in range(0,8,2):
    m[i,::2]=1
    m[i+1,1::2]=1
print(m)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [89]:
# Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.
c=np.array([-17.78, -11.11, 7.34, 1.11, 37.73, 0. ])
f=c*(9/5)+32
print(f)

[-4.0000e-03  1.2002e+01  4.5212e+01  3.3998e+01  9.9914e+01  3.2000e+01]


In [5]:
#Random walks without numpy

import random

values=[-1,1]
steps=[0]+[random.choice(values) for i in range(0,11)]
location=0
for i in steps: location+=i

print(steps)
print(location)

[0, -1, -1, 1, 1, -1, -1, -1, 1, 1, 1, -1]
-1


In [62]:
# Random walks using numpy

import numpy as np

steps=np.random.choice(values,(5000,1001))
steps[:,0]=0

position=steps.sum(axis=1)
walk=steps.cumsum(axis=1)

hit30=(abs(walk)>=30).any(axis=1)

# print(hit30.sum())
print(hit30,"\n"*2)

crossing_positions=(abs(walk[hit30])>=30).argmax(axis=1)
print(crossing_positions)
print(crossing_positions.mean())

# print(steps,"\n"*2)
# print(position,"\n"*2)
# print(walk)
# print(walk)

[ True  True False ... False  True  True] 


[480 906 324 ... 460 266 528]
508.38078396699086


In [38]:
for i,j in enumerate(walk):
    if abs(j)>=2:
        print(i)
        break
    

4


In [9]:
#17 Write a NumPy program to generate a random number between 0 and 1.
import numpy as np
number=np.random.random()
if 1-number<0.001:
    number=1
print(number)

0.8261027499627654


In [10]:
#18 Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.
arr=np.random.standard_normal(15)
print(arr)

[ 0.22290722  0.25015884  0.66730776  2.38610254 -0.45015898 -0.55753806
 -0.32235371 -1.25469407  1.69126855  0.0308669   0.49600717  0.28592178
 -0.32472373  0.95756672  0.14261709]


In [14]:
#19 Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

v=np.arange(15,56)
v[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [17]:
#20 Write a NumPy program to create a 3X4 array and iterate over it.
m=np.random.random((3,4))
for i in m:
    for j in i:
        print(j)

0.3030363206267691
0.15467164580399284
0.946297822545102
0.10003677384153398
0.7352800430102374
0.050265848876077435
0.8542873264301339
0.07300765297912726
0.02187930183467801
0.801760328761841
0.7374711958594639
0.004924593899436114


In [20]:
#21. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

v=np.random.randint(5,51,10)
print(v)

[22 20 12 29 37  6 33 38 10 36]


In [31]:
#22. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.
v=np.arange(21)
v2=np.where((v>=9)&(v<=15),-v,v)
print(v2)


[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [32]:
#23 Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.
v=np.random.randint(0,11,5)
print(v)

[ 5 10  6  4  8]


In [33]:
# 25. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

m=np.random.randint(10,22,(3,4))
print(m)

[[20 15 12 20]
 [18 20 14 16]
 [12 19 14 15]]


In [34]:
#31 Write a NumPy program to create a 3x3x3 array filled with arbitrary values.
m=np.random.random((3,3,3))
print(m)

[[[0.22931636 0.47679472 0.11305905]
  [0.591906   0.88447938 0.71881941]
  [0.87565446 0.93912849 0.17314054]]

 [[0.75802152 0.42232017 0.54769976]
  [0.29990584 0.15008098 0.19200179]
  [0.14173041 0.80707937 0.07299609]]

 [[0.44866439 0.69188291 0.26474041]
  [0.71386085 0.06424272 0.74732638]
  [0.53385534 0.08481337 0.21092122]]]


In [35]:
#  Write a NumPy program to compute the sum of all elements, the sum of each column and the sum of each row in a given array.
x = np.array([[0,1],[2,3]])
print(x.sum())
print("Suma por columna",x.sum(axis=0))
print("Suma por fila",x.sum(axis=1))

6
Suma por columna [2 4]
Suma por fila [1 5]


In [36]:
# 34. Write a NumPy program to add a vector to each row of a given matrix.

m = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 1, 0])

print(m+v)

[[ 2  3  3]
 [ 5  6  6]
 [ 8  9  9]
 [11 12 12]]


In [ ]:
# 37. Write a NumPy program to save a given array to a text file and load it.
x = np.arange(12).reshape(4, 3)
np.save("./ejercicio37.npy",x)

In [40]:
y=np.load("./ejercicio37.npy")
print(y)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [47]:
#40 Write a NumPy program to compute the x and y coordinates for points on a sine curve
points=np.arange(-10,11,0.1)
sin_points=np.sin(points)
grid=list(zip(points,sin_points))
print(grid)

[(-10.0, 0.5440211108893698), (-9.9, 0.45753589377532133), (-9.8, 0.3664791292519284), (-9.700000000000001, 0.2717606264109442), (-9.600000000000001, 0.1743267812229814), (-9.500000000000002, 0.07515112046181108), (-9.400000000000002, -0.02477542545335599), (-9.300000000000002, -0.12445442350705994), (-9.200000000000003, -0.2228899141002442), (-9.100000000000003, -0.31909836234934874), (-9.000000000000004, -0.4121184852417533), (-8.900000000000004, -0.5010208564578816), (-8.800000000000004, -0.5849171928917588), (-8.700000000000005, -0.6629692300821793), (-8.600000000000005, -0.7343970978741098), (-8.500000000000005, -0.798487112623487), (-8.400000000000006, -0.8545989080882778), (-8.300000000000006, -0.9021718337562911), (-8.200000000000006, -0.9407305566797707), (-8.100000000000007, -0.9698898108450846), (-8.000000000000007, -0.9893582466233808), (-7.9000000000000075, -0.9989413418397717), (-7.800000000000008, -0.9985433453746054), (-7.700000000000008, -0.9881682338770016), (-7.60000

In [49]:
#42.Write a NumPy program to add elements to a matrix. If an element in the matrix is 0, we will not add the element below this element.
element=10
m = [[1, 1, 0, 2],
    [0, 3, 0, 3], 
    [1, 0, 4, 4]]
m=np.array(m)
m2=np.where(m==0,m,m+element)
print(m2)

[[11 11  0 12]
 [ 0 13  0 13]
 [11  0 14 14]]


In [57]:
#44. Write a NumPy program to check whether two arrays are equal (element wise) or not.
nums1 = np.array([0.5, 1.5, 0.2])
nums2 = np.array([0.5, 1.500000000, 0.2])
(nums1==nums2).all()


True

In [66]:
# 48. Write a NumPy program to create a two-dimensional array with shape (8,5) of random numbers. Select random numbers from a normal distribution (200,7).
arr=np.random.normal(200,7,(8,5))
print(arr)

[[201.21308011 205.63570255 188.52220797 196.69468033 202.65125825]
 [193.62613554 189.535796   202.85051235 190.71499475 190.63377541]
 [209.04503659 194.80927827 190.50732697 209.9090704  197.50167601]
 [206.81007649 207.01612109 204.5555871  198.536125   202.84359909]
 [202.81252498 198.45207649 204.16647147 200.40191116 189.78132404]
 [199.98803351 193.56953619 199.29197425 202.08862209 190.77050277]
 [194.54275831 196.68157982 210.69886311 208.83656432 204.19093218]
 [205.08280528 202.91345165 204.72136499 197.18533477 203.41570065]]


In [69]:
# 50. Write a NumPy program to create a 4x4 array with random values. Create an array from the said array swapping first and last rows.

arr=np.random.random((4,4))
arr2=arr.copy()
print(arr,"\n"*2)
arr2[0]=arr[-1]
arr2[-1]=arr[0]
print(arr2)

[[0.96432904 0.4936242  0.7310733  0.33358655]
 [0.98992377 0.32740207 0.231299   0.93973218]
 [0.89912022 0.76228989 0.86115068 0.41023588]
 [0.95114629 0.02836876 0.4012403  0.06504849]] 


[[0.95114629 0.02836876 0.4012403  0.06504849]
 [0.98992377 0.32740207 0.231299   0.93973218]
 [0.89912022 0.76228989 0.86115068 0.41023588]
 [0.96432904 0.4936242  0.7310733  0.33358655]]


In [79]:
# 52. Write a NumPy program to sort a given array by row and column in ascending order.
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 4.38, 6.99],
              [1.54, 2.39, 9.29]])

nums_columns=np.sort(nums,axis=0)
nums_rows=np.sort(nums,axis=1)

print(nums_columns,"\n"*3,nums_rows)

[[1.54 2.39 6.99]
 [3.54 3.38 7.99]
 [5.54 4.38 9.29]] 


 [[3.38 5.54 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]


In [80]:
#53. Write a NumPy program to extract all numbers from a given array less and greater than a specified number.

nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 4.38, 6.99],
              [1.54, 2.39, 9.29]])
n=5

print("numbers less than",n,"are",nums[nums<5])
print("numbers greater than",n,"are",nums[nums>5])

numbers less than 5 are [3.38 3.54 4.38 1.54 2.39]
numbers greater than 5 are [5.54 7.99 6.99 9.29]


In [84]:
# 54 Write a NumPy program to replace all numbers in a given array equal, less and greater than a given number.
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 8.32, 6.99],
              [1.54, 2.39, 9.29]])
n=8.32
r=18.32
nums2=np.where(nums==n,r,nums)
print(nums2)

[[ 5.54  3.38  7.99]
 [ 3.54 18.32  6.99]
 [ 1.54  2.39  9.29]]


In [85]:
# 55. Write a NumPy program to create an array of equal shape and data type for a given array.
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 8.32, 6.99],
              [1.54, 2.39, 9.29]])
arr=np.random.random(nums.shape).astype(nums.dtype)
print(arr)

[[0.24101664 0.89294199 0.4388635 ]
 [0.65332425 0.55921072 0.87329824]
 [0.9699596  0.57949116 0.61212477]]


In [88]:
arr=np.array([[[1,2,3,4,5],
             [4,5,6,7,8]],
             
             [[4,6,7,8,9],
              [7,8,9,1,4]]])
print(arr.shape)

(2, 2, 5)


In [89]:
# 57. Write a NumPy program to create a 4x4 array. Create an array from said array by swapping first and last, second and third columns.

arr=np.random.random((4,4))
print(arr,"\n")

arr2=arr.copy()
arr2[0]=arr[-1]
arr2[-1]=arr[0]
arr2[1]=arr[2]
arr2[2]=arr[1]

print(arr2)


[[0.74514477 0.52285541 0.58691269 0.08217855]
 [0.23443969 0.64908957 0.55229613 0.62486087]
 [0.72777769 0.12227655 0.59432861 0.50620745]
 [0.61781617 0.45791668 0.95770383 0.60835176]] 

[[0.61781617 0.45791668 0.95770383 0.60835176]
 [0.72777769 0.12227655 0.59432861 0.50620745]
 [0.23443969 0.64908957 0.55229613 0.62486087]
 [0.74514477 0.52285541 0.58691269 0.08217855]]


In [105]:
# 58. Write a NumPy program to swap rows and columns of a given array in reverse order.

nums = np.array([[[1, 2, 3, 4],
               [0, 1, 3, 4],
               [90, 91, 93, 94],
               [5, 0, 3, 2]]])

nums[::-1,::-1]

array([[[ 5,  0,  3,  2],
        [90, 91, 93, 94],
        [ 0,  1,  3,  4],
        [ 1,  2,  3,  4]]])